server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pop
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: NOTIFICATION-SERVICE
  cloud:
    discovery:
      enabled: true
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
    openfeign:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      properties:
        fetch.max.bytes: 20000000
    producer:
      properties:
        max.request.size: 20000000
    listener:
      max.poll.records: 100

  mail:
    host: smtp.gmail.com
    port: 587
    username: sertacgulertest@gmail.com
    password: 7378221.Sertacgulertest
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
