server:
  port: 8086

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8081
          #uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

        - id: payment-service
          uri: http://localhost:8082
          #uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**

        - id: notification-service
          uri: http://localhost:8083
          #uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**

        - id: customer-service
          uri: http://localhost:8084
          #uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**

        - id: product-service
          uri: http://localhost:8085
          #uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**



eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
