server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pop
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: ORDER-SERVICE
  cloud:
    discovery:
      enabled: true
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service-group
      properties:
        fetch.max.bytes: 20000000
    producer:
      properties:
        max.request.size: 20000000
    listener:
      max.poll.records: 100


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

feign:
  client:
    config:
      default:
        loggerLevel: FULL



